name: Cherry-pick

on:
  pull_request:
    branches:
      - main
    types: ["closed"]

jobs:
  cherry_pick_release_v0_28:
    runs-on: ubuntu-latest
    name: Cherry-pick into release-0.28 brach
    if: ${{ contains(github.event.pull_request.labels.*.name, 'cherry-pick/release-0.28') && github.event.pull_request.merged == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cherry pick into release-0.28
        id: cherrypick
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.9
        with:
          token: ${{ secrets.ALFRED_PAT }}
          committer: Alfred the Narwhal <noreply@github.com>
          author: Alfred the Narwhal <noreply@github.com>
          branch: release-0.28
          title: '[release-0.28] cherry-pick ${{github.event.number}} : {old_title}'
          body: 'Cherry-pick of #{old_pull_request_id} into release-0.28 branch'
          labels: "backports/release-0.28"
  notify_cherrypick_status:
    runs-on: ubuntu-latest
    name: Notify release-0.28 cherry-pick status
    needs: [cherry_pick_release_v0_28]
    if: always()
    steps:
      - name: Check the status of the cherry-pick job
        uses: martialonline/workflow-status@v3
        id: check
      - name: Add cherry-pick status
        uses: peter-evans/create-or-update-comment@v2
        if: steps.check.outputs.status == "failure"
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Failed to create cherry-pick PR, workflow failed (usually due to merge conflcits), please create the cherry-pick PR manually.
      - name: Comment cherry-pick success status
        uses: peter-evans/create-or-update-comment@v2
        if: steps.check.outputs.status == "success"
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Created cherry-pick PR.
      - name: Add cherry-pick workflow cancelled status
        uses: peter-evans/create-or-update-comment@v2
        if: steps.check.outputs.status == "cancelled"
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Cherry-pick workflow is cancelled, please re-run the workflow manually.
